apiVersion: apps/v1
kind: Deployment
metadata:
annotations:
  vault.security.banzaicloud.io/vault-addr: http://192.168.1.10:8200
  vault.security.banzaicloud.io/vault-path: kubernetes
  vault.security.banzaicloud.io/vault-role: test_role
  vault.security.banzaicloud.io/vault-skip-verify: true
  name: ssl-monitoring
  namespace: default
spec:
  selector:
    matchLabels:
      app: ssl-mon
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ssl-mon
    spec:
      containers:
        - image: 239534/ssl-cert-monitor:1.0
          resources:
            requests:
              memory: "20Mi"
          imagePullPolicy: IfNotPresent
          name: ssl-monitoring
          env:
          - name: GRAFANA_APIKEY
            value: vault:kv/data/grafana/#apikey
          - name: ZABBIX_PASSWD
            value: vault:kv/data/zabbix#api_zabbix
          ports:
            - containerPort: 8080